console.log(parseInt('123'));
console.log(parseInt('123px'));
console.log(parseInt('12.34'));
console.log(parseInt('abc'));
console.log(parseInt(''));
console.log(parseInt(null));
console.log(parseInt(undefined));
console.log(parseInt(true));
console.log(parseInt(false));